title: Supply Chain Optimization with DSA 
description: This project demonstrates the application of data structures and algorithms (DSA)
             to optimize a specific aspect of supply chain management.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
